---
job: &job
  public: false
  serial: true

get_source: &get_source
  get: source
  trigger: true

get_source_publish: &get_source_publish
  <<: *get_source
  trigger: false
  passed:
  - test-build

get_version: &get_version
  get: version
  trigger: false

put_version: &put_version
  put: version
  attempts: 3
  params:
    file: version/version

project: &project
  PROJECT: PdfSharpCore

task_publish_nugget: &task_publish_nugget
  task: publish-nugget
  file: source/.ci/tasks/publish-nugget.yaml
  attempts: 3
  params:
    <<: *project
    NUGGET_API_KEY: ((nugget_api_key))
    NUGGET_TAGS: "PdfSharp .NETCore"

#-----------------------------------------------------------------------------------------------------------------------
# Resources
#-----------------------------------------------------------------------------------------------------------------------
resources:
- name: source
  type: git
  source:
    uri: https://github.com/ststeiger/PdfSharpCore.git
    branch: master
    paths:
    - PdfSharpCore

- name: version
  type: semver
  source:
    driver: s3
    bucket: startnow65
    key: concourse/pdfsharpcore-semver
    region_name: us-west-2
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))

#-----------------------------------------------------------------------------------------------------------------------
# Jobs
#-----------------------------------------------------------------------------------------------------------------------
jobs:

# Would be replace with proper Unit/Integration tests
- name: test-build
  <<: *job
  plan:
  - <<: *get_source
  - task: build-project
    file: source/.ci/tasks/build.yaml
    attempts: 3
    params:
      <<: *project

- name: publish-patch
  <<: *job
  plan:
  - in_parallel:
    - <<: *get_source_publish
      trigger: true
    - <<: *get_version
      params:
        bump: patch

  - <<: *put_version
  - <<: *task_publish_nugget

- name: publish-minor
  <<: *job
  plan:
  - in_parallel:
    - <<: *get_source_publish
    - <<: *get_version
      params:
        bump: minor

  - <<: *put_version
  - <<: *task_publish_nugget

- name: publish-major
  <<: *job
  plan:
  - in_parallel:
    - <<: *get_source_publish
    - <<: *get_version
      params:
        bump: major

  - <<: *put_version
  - <<: *task_publish_nugget
