//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraDocCore.DocumentObjectModel.MigraDoc.DocumentObjectModel.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MigraDoc.DocumentObjectModel.MigraDoc.DocumentObjectModel.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base style name must be defined..
        /// </summary>
        internal static string BaseStyleRequired {
            get {
                return ResourceManager.GetString("BaseStyleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bool expected: &apos;{0}&apos;..
        /// </summary>
        internal static string BoolExpected {
            get {
                return ResourceManager.GetString("BoolExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only cells can be compared by this Comparer..
        /// </summary>
        internal static string CompareJustCells {
            get {
                return ResourceManager.GetString("CompareJustCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to set empty base style is invalid..
        /// </summary>
        internal static string EmptyBaseStyle {
            get {
                return ResourceManager.GetString("EmptyBaseStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of file expected..
        /// </summary>
        internal static string EndOfFileExpected {
            get {
                return ResourceManager.GetString("EndOfFileExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence..
        /// </summary>
        internal static string EscapeSequenceNotAllowed {
            get {
                return ResourceManager.GetString("EscapeSequenceNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier expected: &apos;{0}&apos;..
        /// </summary>
        internal static string IdentifierExpected {
            get {
                return ResourceManager.GetString("IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image[Path={0}].
        /// </summary>
        internal static string ImagePathString {
            get {
                return ResourceManager.GetString("ImagePathString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image[{0}].
        /// </summary>
        internal static string ImageTypeString {
            get {
                return ResourceManager.GetString("ImageTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting null into a collection is not allowed..
        /// </summary>
        internal static string InsertNullNotAllowed {
            get {
                return ResourceManager.GetString("InsertNullNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer expected: &apos;{0}&apos;..
        /// </summary>
        internal static string IntegerExpected {
            get {
                return ResourceManager.GetString("IntegerExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid assignment to &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidAssignment {
            get {
                return ResourceManager.GetString("InvalidAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidColor {
            get {
                return ResourceManager.GetString("InvalidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color could not be parsed from string &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidColorString {
            get {
                return ResourceManager.GetString("InvalidColorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given document object is not valid in this context..
        /// </summary>
        internal static string InvalidDocumentObjectType {
            get {
                return ResourceManager.GetString("InvalidDocumentObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidEnum {
            get {
                return ResourceManager.GetString("InvalidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShapePosition must be Left, Center, or Right..
        /// </summary>
        internal static string InvalidEnumForLeftPosition {
            get {
                return ResourceManager.GetString("InvalidEnumForLeftPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShapePosition must be Top, Center, or Bottom..
        /// </summary>
        internal static string InvalidEnumForTopPosition {
            get {
                return ResourceManager.GetString("InvalidEnumForTopPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid numeric field format..
        /// </summary>
        internal static string InvalidFieldFormat {
            get {
                return ResourceManager.GetString("InvalidFieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field type: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidFieldType {
            get {
                return ResourceManager.GetString("InvalidFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font size &apos;{0}&apos; is out of range..
        /// </summary>
        internal static string InvalidFontSize {
            get {
                return ResourceManager.GetString("InvalidFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;Name&apos; of &apos;InfoField&apos; has invalid value &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidInfoFieldName {
            get {
                return ResourceManager.GetString("InvalidInfoFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidRange {
            get {
                return ResourceManager.GetString("InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol not valid &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidSymbolType {
            get {
                return ResourceManager.GetString("InvalidSymbolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable type &apos;{0}&apos; not supported by &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an unknown unit type..
        /// </summary>
        internal static string InvalidUnitType {
            get {
                return ResourceManager.GetString("InvalidUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; is not a valid value for structure &apos;Unit&apos;..
        /// </summary>
        internal static string InvalidUnitValue {
            get {
                return ResourceManager.GetString("InvalidUnitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &apos;{1}&apos; not valid for Value &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidValueForOperation {
            get {
                return ResourceManager.GetString("InvalidValueForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value name: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidValueName {
            get {
                return ResourceManager.GetString("InvalidValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{1}&apos; - &apos;{0}&apos; expected..
        /// </summary>
        internal static string KeyWordExpected {
            get {
                return ResourceManager.GetString("KeyWordExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing left brace after &apos;{0}&apos;..
        /// </summary>
        internal static string MissingBraceLeft {
            get {
                return ResourceManager.GetString("MissingBraceLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing right brace after &apos;{0}&apos;..
        /// </summary>
        internal static string MissingBraceRight {
            get {
                return ResourceManager.GetString("MissingBraceRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing left bracket after &apos;{0}&apos;..
        /// </summary>
        internal static string MissingBracketLeft {
            get {
                return ResourceManager.GetString("MissingBracketLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing right bracket after &apos;{0}&apos;..
        /// </summary>
        internal static string MissingBracketRight {
            get {
                return ResourceManager.GetString("MissingBracketRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing comma..
        /// </summary>
        internal static string MissingComma {
            get {
                return ResourceManager.GetString("MissingComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obigatory property &apos;{0}&apos; not set in &apos;{1}&apos;..
        /// </summary>
        internal static string MissingObligatoryProperty {
            get {
                return ResourceManager.GetString("MissingObligatoryProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing left parenthesis after &apos;{0}&apos;..
        /// </summary>
        internal static string MissingParenLeft {
            get {
                return ResourceManager.GetString("MissingParenLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing right parenthesis after &apos;{0}&apos;..
        /// </summary>
        internal static string MissingParenRight {
            get {
                return ResourceManager.GetString("MissingParenRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newline in string not allowed..
        /// </summary>
        internal static string NewlineInString {
            get {
                return ResourceManager.GetString("NewlineInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied: &apos;{0}&apos; for internal use only..
        /// </summary>
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign &apos;null&apos; to &apos;{0}&apos; not allowed..
        /// </summary>
        internal static string NullAssignmentNotSupported {
            get {
                return ResourceManager.GetString("NullAssignmentNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null expected: &apos;{0}&apos;..
        /// </summary>
        internal static string NullExpected {
            get {
                return ResourceManager.GetString("NullExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number expected: &apos;{0}&apos;..
        /// </summary>
        internal static string NumberExpected {
            get {
                return ResourceManager.GetString("NumberExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error: Operator &apos;{0}&apos; is expected..
        /// </summary>
        internal static string OperatorExpected {
            get {
                return ResourceManager.GetString("OperatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid range only within &apos;{0}&apos;..
        /// </summary>
        internal static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of type &apos;{0}&apos; must be cloned before set into &apos;{1}&apos;..
        /// </summary>
        internal static string ParentAlreadySet {
            get {
                return ResourceManager.GetString("ParentAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real expected: &apos;{0}&apos;..
        /// </summary>
        internal static string RealExpected {
            get {
                return ResourceManager.GetString("RealExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String expected: &apos;{0}&apos;..
        /// </summary>
        internal static string StringExpected {
            get {
                return ResourceManager.GetString("StringExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be of type MigraDoc.DocumentObjectModel.Style..
        /// </summary>
        internal static string StyleExpected {
            get {
                return ResourceManager.GetString("StyleExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid style name &apos;{0}&apos;..
        /// </summary>
        internal static string StyleNameExpected {
            get {
                return ResourceManager.GetString("StyleNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; expected, found &apos;{1}&apos;..
        /// </summary>
        internal static string SymbolExpected {
            get {
                return ResourceManager.GetString("SymbolExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol &apos;{0}&apos; is not an object..
        /// </summary>
        internal static string SymbolIsNotAnObject {
            get {
                return ResourceManager.GetString("SymbolIsNotAnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol &apos;{0}&apos; in this context not allowed..
        /// </summary>
        internal static string SymbolNotAllowed {
            get {
                return ResourceManager.GetString("SymbolNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the following symbols {0} is expected..
        /// </summary>
        internal static string SymbolsExpected {
            get {
                return ResourceManager.GetString("SymbolsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base style name &apos;{0}&apos; is undefined..
        /// </summary>
        internal static string UndefinedBaseStyle {
            get {
                return ResourceManager.GetString("UndefinedBaseStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file..
        /// </summary>
        internal static string UnexpectedEndOfFile {
            get {
                return ResourceManager.GetString("UnexpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected symbol &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedSymbol {
            get {
                return ResourceManager.GetString("UnexpectedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown chart type: &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownChartType {
            get {
                return ResourceManager.GetString("UnknownChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of undefined base style &apos;{0}&apos;..
        /// </summary>
        internal static string UseOfUndefinedBaseStyle {
            get {
                return ResourceManager.GetString("UseOfUndefinedBaseStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of undefined style &apos;{0}&apos;..
        /// </summary>
        internal static string UseOfUndefinedStyle {
            get {
                return ResourceManager.GetString("UseOfUndefinedStyle", resourceCulture);
            }
        }
    }
}
