//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraDocCore.Rendering.MigraDoc.Rendering.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MigraDocCore.Rendering.MigraDoc.Rendering.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark &apos;{0}&apos; is not defined within the document..
        /// </summary>
        internal static string BookmarkNotDefined {
            get {
                return ResourceManager.GetString("BookmarkNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image has empty size..
        /// </summary>
        internal static string DisplayEmptyImageSize {
            get {
                return ResourceManager.GetString("DisplayEmptyImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found..
        /// </summary>
        internal static string DisplayImageFileNotFound {
            get {
                return ResourceManager.GetString("DisplayImageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image could not be read..
        /// </summary>
        internal static string DisplayImageNotRead {
            get {
                return ResourceManager.GetString("DisplayImageNotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image has no valid type..
        /// </summary>
        internal static string DisplayInvalidImageType {
            get {
                return ResourceManager.GetString("DisplayInvalidImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified image size is empty..
        /// </summary>
        internal static string EmptyImageSize {
            get {
                return ResourceManager.GetString("EmptyImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image &apos;{0}&apos; not found..
        /// </summary>
        internal static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image {0} could not be read.\n Inner exception: {1}.
        /// </summary>
        internal static string ImageNotReadable {
            get {
                return ResourceManager.GetString("ImageNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image type: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidImageType {
            get {
                return ResourceManager.GetString("InvalidImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number {0} is too large to be displayed as letters..
        /// </summary>
        internal static string NumberTooLargeForLetters {
            get {
                return ResourceManager.GetString("NumberTooLargeForLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number {0} is too large to be displayed as roman..
        /// </summary>
        internal static string NumberTooLargeForRoman {
            get {
                return ResourceManager.GetString("NumberTooLargeForRoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only images, textframes, charts and paragraphs can be rendered freely..
        /// </summary>
        internal static string ObjectNotRenderable {
            get {
                return ResourceManager.GetString("ObjectNotRenderable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be set before calling &apos;{1}&apos;..
        /// </summary>
        internal static string PropertyNotSetBefore {
            get {
                return ResourceManager.GetString("PropertyNotSetBefore", resourceCulture);
            }
        }
    }
}
